apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
spec:
  selector:
    matchLabels:
      name: service-template
  template:
    metadata:
      labels:
        name: service-template
    spec:
      containers:
        - name: service-template
          image: {{AWS_ACCOUNT_ID}}.dkr.ecr.eu-central-1.amazonaws.com/service-template
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: KAFKA_API_KEY
            - name: KAFKA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: KAFKA_API_SECRET
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: kafka
                  key: KAFKA_BOOTSTRAP_SERVER
            - name: K8S_RDS_HOST
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: K8S_RDS_HOST
            - name: K8S_RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: K8S_RDS_DB_NAME
            - name: K8S_RDS_MASTER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: K8S_RDS_MASTER_USERNAME
            - name: K8S_RDS_MASTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds
                  key: K8S_RDS_MASTER_PASSWORD
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: service-template
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /service-template/api/health-check
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: service-template
